[package]
name = "threadbag"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.9.0"
anyhow = "1.0.80"
serde = { version="1.0.196", features = ["derive"] } 
actix-web = "4.5.1"
tokio = { version = "1", features = ["full"] }
subxt = "0.33.0"
subxt-signer = "0.33.0"
serde_json = "1.0.114"
sled = "0.34.7"
getrandom = "0.2.12"
flate2 = "1.0.28"
base64 = "0.21.7"
