[package]
name = "threadbag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.9.0"
anyhow = "1.0.80"
serde = { version="1.0.196", features = ["derive"] } 
actix-web = "4.5"
tokio = { version = "1", features = ["full"] }
subxt = "0.33.0"
subxt-signer = "0.33.0"